language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - .+
# Needed to get java 8u51 because 8u31, which is available from sudo: false causes compile errors
sudo: required
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
before_install:
- export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- openssl aes-256-cbc -K $encrypted_143bf53fc355_key -iv $encrypted_143bf53fc355_iv -in services.tar.enc -out services.tar -d
- tar xvf services.tar
- curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
- java -jar jpm4j.jar -u init
- ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
- wget https://raw.githubusercontent.com/JakeWharton/pidcat/master/pidcat.py
install:
- git fetch --unshallow --tags
before_script:
- echo no | android create avd -f -n test -t android-19 -b armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0
- adb shell settings put global transition_animation_scale 0
- adb shell settings put global animator_duration_scale 0
- ./gradlew clean
- adb logcat -c
script:
- ./gradlew assembleRegularRelease
- adb shell input keyevent 82 &
- ./gradlew createRegularDebugCoverageReport
- adb logcat -d | ~/pidcat.py de.dreier.mytargets.debug | tee app/build/reports/androidTests/connected/flavors/REGULAR/logcat.log
- adb logcat -c
- ./gradlew jacocoTestRegularDebugUnitTestReport
- adb logcat -d | ~/pidcat.py de.dreier.mytargets.debug | tee app/build/reports/tests/connected/flavors/REGULAR/logcat.log
after_success:
- |
  if [[ "$TRAVIS_TAG" ]]; then
    ./gradlew publishRegularRelease
    ./gradlew -PFirebaseServiceAccountFilePath=app/src/main/google-services.json :app:firebaseUploadRegularReleaseProguardMapping
    ./dropbox_uploader.sh upload app/build/outputs/apk/app-regular-release.apk /Release/$TRAVIS_TAG/MyTargets.apk
    ./dropbox_uploader.sh upload app/build/outputs/mapping/regular/release/mapping.txt /Release/$TRAVIS_TAG/mapping.txt
  fi
- bash <(curl -s https://codecov.io/bash)
- ~/jpm/bin/codacy-coverage-reporter -l Java -r app/build/reports/coverage/regular/debug/report.xml
after_failure:
- chmod +x dropbox_uploader.sh
- ln -s app/build/reports/androidTests/connected/flavors/REGULAR androidTests
- ln -s app/build/reports/tests/connected/flavors/REGULAR tests
- zip -r reports.zip androidTests tests
- ./dropbox_uploader.sh upload reports.zip /Reports/$TRAVIS_JOB_NUMBER.zip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Iz8i8L5YlrCq7KdkKNenb4wKQR0TrtR3eoJ/e0U/jsZb3CGqNru0HtatJTCvggR/Md5FGCmk6LD2Wl9usbIv6rn2F5T4GSSYxRtYZ4124zt+GyEU3jAlgJt72AJEIAVFjTtWAcM9mUc8QME/iOeDbbZUt6LV+IP1UbY472K6+R4sd/ChRq4tRAlK/kMjGgoBjXH9iV+RZkjrGvHwHc8UsOUPnl/4PhqLBda+SYDsjZWOQCnNUv8G2dTlHnbgF6eIKjHR4NpAIHYEqkTE5YV7aWjKQy4UGFZStkqhiaMpfntJ+KJWr/fOaKwwxIq3JuBUC0fbyj81q5Yf/zvGOmkeejU3K28+sWfYKD016JbWh58GuOY5OCXRd8SmnMG3kndhAZ3GmgmJClvK+cW8wtF1xOmnoSHaeB48y2VIDrZ1yZm5aZ/dgUUTxaKzVfZpqo1JL4PWm6l1vU4+tp89ds3oynpVowkZxjgH5kr9f10fe+oOtTY6lrUIvZbDIL74/EEV2YFMe2ittjRlBm2En3cOvpisEqYGZwm4yFrZ45fhSQui12NiUrXHBfrAbX/qT+VSH0OCmYxm6muPz/XJCXIcl1zTwj6kiFF0Dw3paTsYbkaDQRXHvdJIr8PBDcSZSrP9kyyQjaog0HtS7OqXbugw6qDaya9+zkHVy4LWVDOpEYM=
  file: app/build/outputs/apk/app-regular-release.apk
  on:
    tags: true
    repo: DreierF/MyTargets
    branch: develop
