language: android
jdk:
- oraclejdk8
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.2
  - EMULATOR_API_LEVEL=19
  - ANDROID_ABI=armeabi-v7a
  - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - JAVA_HOME=$JAVA8_HOME
  - PWD=`pwd`
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  # Google Play Services
  - extra-google-google_play_services
  # Support library
  - extra-android-support
  # Latest artifacts in local repository
  - extra-google-m2repository
  - extra-android-m2repository
  # Specify at least one system image
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
before_install:
- openssl aes-256-cbc -K $encrypted_143bf53fc355_key -iv $encrypted_143bf53fc355_iv -in services.tar.enc -out services.tar -d
- tar xvf services.tar
- wget https://raw.githubusercontent.com/JakeWharton/pidcat/master/pidcat.py
install:
# Converts the shallow clone to a full clone
# This is necessary in order to determine the current app version code
- git fetch --unshallow --tags
before_script:
- echo no | android create avd -f -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI -s WVGA800 -c 128M
- emulator -avd test -no-audio -no-window &
- ./gradlew clean
script:
- echo -e '\033[0;33mBuilding...\033[0m' && echo -en 'travis_fold:start:script.build\\r'
- ./gradlew assembleRegularRelease -PdisablePreDex
- echo -en 'travis_fold:end:script.build\\r'

- echo -e '\033[0;33mUnit tests...\033[0m' && echo -en 'travis_fold:start:script.unittest\\r'
- ./gradlew testRelease jacocoTestReport -PdisablePreDex
- echo -en 'travis_fold:end:script.unittest\\r'

- echo -e '\033[0;33mUI tests...\033[0m' && echo -en 'travis_fold:start:script.uitest\\r'
- android-wait-for-emulator
- adb shell settings put global window_animation_scale 0
- adb shell settings put global transition_animation_scale 0
- adb shell settings put global animator_duration_scale 0
- adb shell input keyevent 82 &
- adb logcat -c
- travis_wait ./gradlew createRegularDebugCoverageReport -PdisablePreDex
- echo -en 'travis_fold:end:script.uitest\\r'

after_success:
- |
  if [[ "$TRAVIS_TAG" ]]; then
    ./gradlew bootstrapRegularReleasePlayResources publishRegularRelease
    ./gradlew -PFirebaseServiceAccountFilePath=$PWD/app/src/release/google-services.json :app:firebaseUploadRegularReleaseProguardMapping
    ./dropbox_uploader.sh upload app/build/outputs/apk/app-regular-release.apk /Release/$TRAVIS_TAG/MyTargets.apk
    ./dropbox_uploader.sh upload app/build/outputs/mapping/regular/release/mapping.txt /Release/$TRAVIS_TAG/mapping.txt
  fi
- bash <(curl -s https://codecov.io/bash)
- ./gradlew sendCoverageToCodacy -PdisablePreDex
after_failure:
- >
  adb logcat -d 2>&1 | python pidcat.py de.dreier.mytargets.debug | tee logcat.log &&
  cd app/build/reports/androidTests/connected/flavors/REGULAR/ &&
  mv ../../../../../../../logcat.log logcat.log &&
  zip -r reports.zip . &&
  cd ../../../../../../.. &&
  ./dropbox_uploader.sh upload app/build/reports/androidTests/connected/flavors/REGULAR/reports.zip /Reports/$TRAVIS_JOB_NUMBER.zip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Iz8i8L5YlrCq7KdkKNenb4wKQR0TrtR3eoJ/e0U/jsZb3CGqNru0HtatJTCvggR/Md5FGCmk6LD2Wl9usbIv6rn2F5T4GSSYxRtYZ4124zt+GyEU3jAlgJt72AJEIAVFjTtWAcM9mUc8QME/iOeDbbZUt6LV+IP1UbY472K6+R4sd/ChRq4tRAlK/kMjGgoBjXH9iV+RZkjrGvHwHc8UsOUPnl/4PhqLBda+SYDsjZWOQCnNUv8G2dTlHnbgF6eIKjHR4NpAIHYEqkTE5YV7aWjKQy4UGFZStkqhiaMpfntJ+KJWr/fOaKwwxIq3JuBUC0fbyj81q5Yf/zvGOmkeejU3K28+sWfYKD016JbWh58GuOY5OCXRd8SmnMG3kndhAZ3GmgmJClvK+cW8wtF1xOmnoSHaeB48y2VIDrZ1yZm5aZ/dgUUTxaKzVfZpqo1JL4PWm6l1vU4+tp89ds3oynpVowkZxjgH5kr9f10fe+oOtTY6lrUIvZbDIL74/EEV2YFMe2ittjRlBm2En3cOvpisEqYGZwm4yFrZ45fhSQui12NiUrXHBfrAbX/qT+VSH0OCmYxm6muPz/XJCXIcl1zTwj6kiFF0Dw3paTsYbkaDQRXHvdJIr8PBDcSZSrP9kyyQjaog0HtS7OqXbugw6qDaya9+zkHVy4LWVDOpEYM=
  file: app/build/outputs/apk/app-regular-release.apk
  on:
    tags: true
    repo: DreierF/MyTargets
    branch: develop
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email: false
